services:
  db:
    container_name: mysql
    image: mysql
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "projetjeeentreprise"
    ports:
      - "3306:3306"

